---
- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: Build puzzle15-tomcat docker image and push it to Docker Hub
  block:
    - name: Copy puzzle15-tomcat source files to build directory
      ansible.builtin.copy:
        src: puzzle15-tomcat
        dest: "{{ build_dir.path }}"

    - name: Build puzzle15-tomcat docker image and push it to Docker Hub
      community.docker.docker_image:
        build:
          path: "{{ build_dir.path }}/puzzle15-tomcat"
        name: abegorov/puzzle15-tomcat
        tag: latest
        push: true
        source: build
        state: present

  always:
    - name: Remove temporary build directory
      ansible.builtin.file:
        path: "{{ build_dir.path }}"
        state: absent
