# https://docs.docker.com/engine/install/ubuntu/
---
- name: Update the apt package index and install packages to allow apt to use a repository over HTTPS
  ansible.builtin.apt:
    name:
      - ca-certificates
      - gnupg
    update_cache: true
    state: present

- name: Create /etc/apt/keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    owner: root
    group: root
    mode: '0755'
    state: directory
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: '0644'
    checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570
  ignore_errors: "{{ ansible_check_mode }}"

- name: Gather distribution_release facts
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - "distribution_release"

- name: Setup Docker's official repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present
